from abc import ABC, abstractmethod
from typing import Any

from . import binary as binary
from . import traced as traced
from . import nary as nary

class CancelToken(ABC):
    def __init__(self) -> None: ...
    @abstractmethod
    def cancel(self) -> None: ...
    @abstractmethod
    def is_cancelled(self) -> bool: ...


class PyState(ABC):
    def __init__(self) -> None: ...
    @abstractmethod
    def step(self, event: Any) -> PyState: ...


class GenericResult:
    def __init__(self, r: int) -> None: ...
    def is_dead(self) -> bool: ...
    def is_accepted(self) -> bool: ...
    def raw_score(self) -> int: ...


class GenericResultInterpretor:
    def __init__(self) -> None: ...
