import enum
from typing import Generic, TypeVar
from lib_ramis import CancelToken, PyState, GenericResult

_BinaryStateT = TypeVar("_BinaryStateT", bound=PyState[BinaryEvent])

class BinaryEvent(enum.Enum):
    No = 0
    Yes = 1

class BinaryBFSStep(Generic[_BinaryStateT]):
    def state(self) -> _BinaryStateT: ...

class BinaryBFS(Generic[_BinaryStateT]):
    def __init__(self, state: _BinaryStateT) -> None: ...
    def next(self, cancel_token: CancelToken) -> BinaryBFSStep[_BinaryStateT] | None: ...
    def put_result(self, step: BinaryBFSStep[_BinaryStateT], result: GenericResult) -> None: ...
    def notify_done(self) -> None: ...
    def is_cancelled(self, item: BinaryBFSStep[_BinaryStateT]) -> bool: ...
