import asyncio

class DDMinPath:
    def to_list(self) -> list[bool]: ...

class BFScheduler:
    def __init__(self) -> None: ...
    def next(self, cancel_token: asyncio.Event) -> PyScheduledStep | None: ...
    def put_result(self, path: PyScheduledStep, event: ReductionStepResult) -> None: ...

class PyScheduledStep:
    def path(self) -> DDMinPath: ...

class DDMinEventInterpretor:
    def __init__(self) -> None: ...

class ReductionStepResult:
    @staticmethod
    def new(r: int) -> ReductionStepResult: ...
    def is_dead(self) -> bool: ...
    def is_accepted(self) -> bool: ...
    def raw_score(self) -> int: ...
