from typing import Generic, Protocol, TypeVar
from lib_ramis import CancelToken, PyState, GenericResult

class NAryEvent(Protocol):
    @property
    def index(self) -> int: ...

_NaryStateT = TypeVar("_NaryStateT", bound=PyState[NAryEvent], covariant=True)
_NaryStateT_inv = TypeVar("_NaryStateT_inv", bound=PyState[NAryEvent])

class NAryStep(Protocol, Generic[_NaryStateT]):
    @property
    def state(self) -> _NaryStateT: ...

class NAryBFS(Protocol, Generic[_NaryStateT_inv]):
    @property
    def branching_factor(self) -> int: ...
    def next(self, cancel_token: CancelToken) -> NAryStep[_NaryStateT_inv] | None: ...
    def put_result(self, step: NAryStep[_NaryStateT_inv], result: GenericResult) -> None: ...
    def notify_done(self) -> None: ...
    def is_cancelled(self, item: NAryStep[_NaryStateT_inv]) -> bool: ...

def create_nary_scheduler(
    branching_factor: int, state: _NaryStateT_inv
) -> NAryBFS[_NaryStateT_inv]: ...
