from typing import override
from . import CancelToken, GenericResult


class Trace:
    def to_list(self) -> list[bool]: ...
    @override
    def __str__(self) -> str: ...
    @override
    def __repr__(self) -> str: ...


class TracedStep:
    def path(self) -> Trace: ...


class TracedBFS:
    def __init__(self) -> None: ...
    def next(self, cancel_token: CancelToken) -> TracedStep | None: ...
    def put_result(self, step: TracedStep, result: GenericResult) -> None: ...
    def notify_done(self) -> None: ...
    def is_cancelled(self, item: TracedStep) -> bool: ...
