from typing import Any, Optional

from lib_ramis import CancelToken

class DDMinPath:
    def to_list(self) -> list[bool]: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class ReductionStepResult:
    @staticmethod
    def new(r: int) -> "ReductionStepResult": ...
    def is_dead(self) -> bool: ...
    def is_accepted(self) -> bool: ...
    def raw_score(self) -> int: ...

class PyScheduledStep:
    def path(self) -> DDMinPath: ...

class BFScheduler:
    def __init__(self) -> None: ...

    def next(self, cancel_token: CancelToken) -> Optional[PyScheduledStep]: ...

    def put_result(self, path: PyScheduledStep, event: ReductionStepResult) -> None: ...

class DDMinEventInterpretor:
    def __init__(self) -> None: ...
